=== MyJVN/np/schemas/oka/myjvn_statistics_1.0.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "https://jvndb.jvn.jp/schema/myjvn_statistics_1.0.json?20250419",
  "title": "MyJVN Statistics",
  "description": "Ver 1.0 (20250419): Representation of MyJVN Statistics as a JSON document.",
  "type": "object",
  "properties": {
    "generator": { "$ref": "#/$defs/generator_type" },
    "title": { "type": "string" },
    "link": { "type": "string", "format": "uri" },
    "updated": { "type": "string", "format": "date-time" },
    "lang": { "type": "string", "enum": ["ja", "en"] },
    "author": { "$ref": "#/$defs/author_type" },
    "distribution": { "$ref": "#/$defs/distribution_type" },
    "dataTotal": { "$ref": "#/$defs/dataTotal_type" },
    "dataFilter": { "$ref": "#/$defs/dataFilter_type" },
    "data": { "$ref": "#/$defs/data_type" },
    "status": { "$ref": "#/$defs/status_type" }
  },
  "$defs": {
    "engine_type": {
      "type": "object",
      "properties": {
        "version": { "type": "string" },
        "name": { "type": "string" }
      }
    },
    "generator_type": {
      "type": "object",
      "properties": {
        "engine": { "$ref": "#/$defs/engine_type" }
      }
    },
    "author_type": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "uri": { "type": "string", "format": "uri" }
      }
    },
    "tlp_type": {
      "title": "Traffic Light Protocol (TLP)",
      "description": "Provides details about the TLP classification of the document.",
      "type": "object",
      "required": ["label"],
      "properties": {
        "label": {
          "title": "Label of TLP",
          "description": "Provides the TLP label of the document.",
          "type": "string",
          "default": "CLEAR",
          "enum": ["AMBER", "AMBER+STRICT", "CLEAR", "GREEN", "RED"]
        },
        "url": {
          "title": "URL of TLP version",
          "description": "Provides a URL where to find the textual description of the TLP version which is used in this document. Default is the URL to the definition by FIRST.",
          "type": "string",
          "default": "https://www.first.org/tlp/",
          "format": "uri",
          "examples": ["https://www.us-cert.gov/tlp"]
        }
      }
    },
    "distribution_type": {
      "title": "Rules for sharing document",
      "description": "Describe any constraints on how this document might be shared.",
      "type": "object",
      "required": ["tlp"],
      "properties": {
        "text": {
          "title": "Textual description",
          "description": "Provides a textual description of additional constraints.",
          "type": "string",
          "minLength": 1,
          "examples": ["Copyright 2025, IPA, All Rights Reserved."]
        },
        "tlp": { "$ref": "#/$defs/tlp_type" }
      }
    },
    "dataTotal_type": {
      "type": "object",
      "properties": {
        "vulninfo": { "type": "integer" },
        "vendor": { "type": "integer" },
        "product": { "type": "integer" }
      }
    },
    "dataFilter_type": {
      "type": "object",
      "properties": {
        "nameType": { "type": "string" },
        "productName": { "type": "string" },
        "cweId": { "type": "string" },
        "metricType": { "type": "string" },
        "pubStartDate": { "type": "string" },
        "pubEndDate": { "type": "string" }
      }
    },
    "vulninfo_type": {
      "type": "object",
      "properties": {
        "1": { "type": "integer" },
        "2": { "type": "integer" },
        "3": { "type": "integer" },
        "4": { "type": "integer" },
        "5": { "type": "integer" },
        "6": { "type": "integer" },
        "7": { "type": "integer" },
        "8": { "type": "integer" },
        "9": { "type": "integer" },
        "10": { "type": "integer" },
        "11": { "type": "integer" },
        "12": { "type": "integer" }
      }
    },
    "data_type": {
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "year": { "type": "integer" },
          "total_vulninfo": { "type": "integer" },
          "total_severity_critical": { "type": "integer" },
          "total_severity_high": { "type": "integer" },
          "total_severity_medium": { "type": "integer" },
          "total_severity_low": { "type": "integer" },
          "total_severity_none": { "type": "integer" },
          "vulninfo": { "$ref": "#/$defs/vulninfo_type" },
          "severity_critical": { "$ref": "#/$defs/vulninfo_type" },
          "severity_high": { "$ref": "#/$defs/vulninfo_type" },
          "severity_medium": { "$ref": "#/$defs/vulninfo_type" },
          "severity_low": { "$ref": "#/$defs/vulninfo_type" },
          "severity_none": { "$ref": "#/$defs/vulninfo_type" }
        },
        "required": [
          "severity_none",
          "total_severity_medium",
          "year",
          "total_severity_low",
          "severity_medium",
          "total_severity_high",
          "severity_low",
          "total_vulninfo",
          "vulninfo",
          "severity_high",
          "total_severity_none",
          "total_severity_critical",
          "severity_critical"
        ]
      }
    },
    "status_type": {
      "type": "object",
      "properties": {
        "version": { "type": "string" },
        "method": { "type": "string" },
        "feed": { "type": "string" },
        "lang": { "type": "string" },
        "retCd": { "type": "integer" },
        "retMax": { "type": "integer" },
        "errCd": { "type": "string" },
        "errMsg": { "type": "string" },
        "totalRes": { "type": "integer" },
        "totalResRet": { "type": "integer" },
        "firstRes": { "type": "integer" }
      },
      "required": ["version", "method", "feed", "retCd"]
    }
  }
}

=== MyJVN/np/examples/oka/getStatistics_oka.json
{
  "$schema": "https://jvndb.jvn.jp/schema/myjvn_statistics_1.0.json?20250419",
  "generator": {
    "date": "2025-04-30T11:36:12+09:00",
    "engine": {
      "version": "4.0.0",
      "name": "MyJVN API"
    }
  },
  "title": "JVNDB 脆弱性対策統計データ",
  "link": "https://jvndb.jvn.jp/apis/myjvn/",
  "updated": "",
  "lang": "ja",
  "author": {
    "name": "IPA",
    "uri": "https://www.ipa.go.jp/"
  },
  "distribution": {
    "tlp": {
      "label": "CLEAR",
      "url": "https://www.first.org/tlp/"
    }
  },
  "dataTotal": {
    "vulninfo": 234395,
    "vendor": 30055,
    "product": 77881
  },
  "dataFilter": {
    "nameType": "",
    "productName": "",
    "cweId": "",
    "metricType": "cvssV3",
    "datePublicStart": "2024",
    "datePublicEnd": "2025"
  },
  "data": [
    {
      "year": 2024,
      "total_vulninfo": 21085,
      "total_severity_critical": 2816,
      "total_severity_high": 7578,
      "total_severity_medium": 10322,
      "total_severity_low": 369,
      "total_severity_none": 0,

      "vulninfo": {
        "1": 1416,
        "2": 1733,
        "3": 1716,
        "4": 1467,
        "5": 1383,
        "6": 1838,
        "7": 1884,
        "8": 2189,
        "9": 1933,
        "10": 2313,
        "11": 1943,
        "12": 1270
      },
      "severity_critical": {
        "1": 307,
        "2": 258,
        "3": 193,
        "4": 150,
        "5": 154,
        "6": 247,
        "7": 207,
        "8": 396,
        "9": 225,
        "10": 259,
        "11": 244,
        "12": 176
      },
      "severity_high": {
        "1": 426,
        "2": 570,
        "3": 552,
        "4": 563,
        "5": 463,
        "6": 575,
        "7": 710,
        "8": 834,
        "9": 716,
        "10": 847,
        "11": 878,
        "12": 444
      },
      "severity_medium": {
        "1": 648,
        "2": 881,
        "3": 935,
        "4": 732,
        "5": 748,
        "6": 985,
        "7": 922,
        "8": 930,
        "9": 952,
        "10": 1158,
        "11": 795,
        "12": 636
      },
      "severity_low": {
        "1": 35,
        "2": 24,
        "3": 36,
        "4": 22,
        "5": 18,
        "6": 31,
        "7": 45,
        "8": 29,
        "9": 40,
        "10": 49,
        "11": 26,
        "12": 14
      },
      "severity_none": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0,
        "5": 0,
        "6": 0,
        "7": 0,
        "8": 0,
        "9": 0,
        "10": 0,
        "11": 0,
        "12": 0
      }
    },
    {
      "year": 2025,
      "total_vulninfo": 2418,
      "total_severity_critical": 441,
      "total_severity_high": 808,
      "total_severity_medium": 1126,
      "total_severity_low": 43,
      "total_severity_none": 0,

      "vulninfo": {
        "1": 762,
        "2": 811,
        "3": 741,
        "4": 104
      },
      "severity_critical": {
        "1": 94,
        "2": 110,
        "3": 201,
        "4": 36
      },
      "severity_high": {
        "1": 277,
        "2": 288,
        "3": 203,
        "4": 40
      },
      "severity_medium": {
        "1": 382,
        "2": 402,
        "3": 317,
        "4": 25
      },
      "severity_low": {
        "1": 9,
        "2": 11,
        "3": 20,
        "4": 3
      },
      "severity_none": {
        "1": 0,
        "2": 0,
        "3": 0,
        "4": 0
      }
    }
  ],
  "status": {
    "version": "4.0.0",
    "method": "getStatistics",
    "feed": "oka",
    "lang": "ja",
    "retCd": 0,
    "retMax": 10000,
    "errCd": "",
    "errMsg": "",
    "totalRes": 16,
    "totalResRet": 16,
    "firstRes": 1
  }
}
