=== MyJVN/np/schemas/myjvn_vuldef_1.0.vulinfo.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "$id": "https://jvndb.jvn.jp/schema/myjvn_vuldef_1.0.vulinfo.json?20250419",
  "title": "VULDEF (VULINFO) - The Vulnerability Data Publication and Exchange Format Data Model for MyJVN",
  "description": "Ver 1.0 (20250419): Representation Data feed of Vulnerability Data Publication and Exchange for MyJVN as a JSON document.",
  "type": "object",
  "$comment": "vulinfo_type",
  "properties": {
    "generator": { "$ref": "#/$defs/generator_type" },
    "title": { "type": "string" },
    "systemid": { "type": "string" },
    "link": {
      "type": "string",
      "format": "uri"
    },
    "updated": {
      "type": "string",
      "format": "date-time"
    },
    "VULDEF-Document": { "$ref": "#/$defs/VULDEF-Document_type" },
    "status": { "$ref": "#/$defs/status_type" }
  },
  "$defs": {
    "engine_type": {
      "type": "object",
      "properties": {
        "version": { "type": "string" },
        "name": { "type": "string" }
      }
    },
    "generator_type": {
      "type": "object",
      "properties": {
        "engine": { "$ref": "#/$defs/engine_type" }
      }
    },
    "VULDEF-Document_type": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "document": {
            "$ref": "csaf_json_schema_2.1.json#/properties/document"
          },
          "product_tree": {
            "$ref": "csaf_json_schema_2.1.json#/properties/product_tree"
          },
          "vulnerabilities": {
            "$ref": "csaf_json_schema_2.1.json#/properties/vulnerabilities"
          },
          "jvn_extension": {
            "$ref": "jvnpid_extension_1.0.json#/$defs/jvn_extension_type"
          }
        }
      }
    },
    "status_type": {
      "type": "object",
      "properties": {
        "version": { "type": "string" },
        "method": { "type": "string" },
        "feed": { "type": "string" },
        "lang": { "type": "string" },
        "retCd": { "type": "integer" },
        "retMax": { "type": "string" },
        "errCd": { "type": "string" },
        "errMsg": { "type": "string" },
        "totalRes": { "type": "string" },
        "totalResRet": { "type": "string" },
        "firstRes": { "type": "string" }
      }
    }
  }
}

=== MyJVN/np/examples/dataFeed_jvndb_detail_oka.json
{
  "$schema": "https://jvndb.jvn.jp/schema/myjvn_vuldef_1.0.vulinfo.json?20250419",
  "generator": {
    "engine": {
      "version": "4.0.0",
      "name": "MyJVN API"
    }
  },
  "title": "JVNDB 脆弱性対策詳細情報",
  "systemid": "jvnpid:1.0::ipa:myjvn_api_getVulnDetailInfo:4.0.0",
  "link": "https://jvndb.jvn.jp/apis/myjvn/",
  "updated": "2025-04-02T00:38:11+09:00",
  "VULDEF-Document": [
    {
      "document": {
        "category": "myjvn_security_advisory",
        "csaf_version": "2.1",
        "distribution": {
          "tlp": {
            "label": "CLEAR",
            "url": "https://www.first.org/tlp/"
          }
        },
        "title": "エアバッグコントロールユニットにおける暗号アルゴリズムの使用に関する脆弱性",
        "lang": "ja",
        "notes": [
          {
            "category": "description",
            "text": "2014 年以降に製造された不特定の乗用車のエアバッグコントロールユニット (別名 pyrotechnical control unit または PCU) には、暗号アルゴリズムの使用に関する脆弱性が存在します。"
          }
        ],
        "tracking": {
          "generator": {
            "engine": {
              "version": "4.0.0",
              "name": "MyJVN API"
            }
          },
          "id": "JVNDB-2017-009608",
          "current_release_date": "2025-04-06T03:00:00+09:00",
          "initial_release_date": "2017-11-16T15:06:40+09:00",
          "status": "final",
          "version": "2.0.0",
          "revision_history": [
            {
              "date": "2018-02-17T10:37:52+09:00",
              "number": "1.0.0",
              "summary": "[2017年11月16日] 掲載"
            },
            {
              "date": "2025-04-06T02:00:00+09:00",
              "number": "2.0.0",
              "summary": "XML形式からJSON形式に変換"
            }
          ]
        },
        "publisher": {
          "category": "coordinator",
          "name": "IPA",
          "namespace": "https://www.ipa.go.jp"
        },
        "references": [
          {
            "category": "external",
            "summary": "CVE-2017-14937",
            "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-14937",
            "type": "advisory",
            "source": "Common Vulnerabilities and Exposures (CVE)"
          },
          {
            "category": "external",
            "summary": "CVE-2017-14937",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-14937",
            "type": "advisory",
            "source": "National Vulnerability Database (NVD)"
          },
          {
            "category": "external",
            "summary": "Vulnerability in pyrotechnical control units of passenger cars",
            "url": "http://www.mmt.hs-karlsruhe.de/downloads/IEEM/Schwachstellen/PCU_Vulnerability_Description_HsKA.PDF",
            "type": "advisory",
            "source": "関連文書"
          }
        ]
      },
      "product_tree": {
        "branches": [
          {
            "category": "vendor",
            "name": "PCU",
            "product": {
              "product_id": "jvnpid:1.0::pcu:pcu",
              "name": "PCU",
              "product_identification_helper": {
                "cpe": "cpe:2.3:h:pcu:pcu:*:*:*:*:*:*:*:*"
              }
            }
          }
        ]
      },
      "vulnerabilities": [
        {
          "cve": "CVE-2017-14937",
          "cwes": [
            {
              "id": "CWE-327",
              "name": "不完全、または危険な暗号アルゴリズムの使用",
              "version": "",
              "source": "NVD"
            }
          ],
          "product_status": {
            "known_affected": ["jvnpid:1.0::pcu:pcu"]
          },
          "threats": [
            {
              "category": "impact",
              "details": "情報を取得される可能性があります。"
            }
          ],
          "remediations": [
            {
              "category": "vendor_fix",
              "details": "参考情報を参照して適切な対策を実施してください。",
              "product_ids": ["jvnpid:1.0::pcu:pcu"]
            }
          ],
          "metrics": [
            {
              "content": {
                "cvss_v2": {
                  "version": "2.0",
                  "vectorString": "AV:L/AC:M/Au:N/C:P/I:N/A:N",
                  "baseScore": 1.9,
                  "baseSeverity": "LOW",
                  "accessVector": "LOCAL",
                  "accessComplexity": "MEDIUM",
                  "authentication": "NONE",
                  "confidentialityImpact": "PARTIAL",
                  "integrityImpact": "NONE",
                  "availabilityImpact": "NONE"
                },
                "cvss_v3": {
                  "version": "3.0",
                  "vectorString": "CVSS:3.0/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
                  "baseScore": 4.7,
                  "baseSeverity": "MEDIUM",
                  "attackVector": "LOCAL",
                  "attackComplexity": "HIGH",
                  "privilegesRequired": "LOW",
                  "userInteraction": "NONE",
                  "scope": "UNCHANGED",
                  "confidentialityImpact": "HIGH",
                  "integrityImpact": "NONE",
                  "availabilityImpact": "NONE"
                },
                "source": "NVD",
                "type": "Primary"
              },
              "products": ["jvnpid:1.0::pcu:pcu"]
            }
          ]
        }
      ],
      "jvn_extension": {
        "generator": {
          "engine": {
            "version": "4.0.0",
            "name": "MyJVN API"
          }
        },
        "title": "JVNDB 脆弱性対策詳細情報",
        "systemid": "jvnpid:1.0::ipa:myjvn_api_getVulnDetailInfo:4.0.0",
        "link": "https://jvndb.jvn.jp/apis/myjvn/",
        "vulnid": "JVNDB-2017-009608"
      }
    },
    {
      "document": {
        "category": "myjvn_security_advisory",
        "csaf_version": "2.1",
        "distribution": {
          "tlp": {
            "label": "CLEAR",
            "url": "https://www.first.org/tlp/"
          }
        },
        "title": "JP1/VERITAS 製品における複数の脆弱性",
        "lang": "ja",
        "notes": [
          {
            "category": "description",
            "text": "JP1/VERITAS 製品に複数の脆弱性が存在します。"
          }
        ],
        "tracking": {
          "generator": {
            "engine": {
              "version": "4.0.0",
              "name": "MyJVN API"
            }
          },
          "id": "JVNDB-2018-009328",
          "current_release_date": "2025-04-06T03:00:00+09:00",
          "initial_release_date": "2018-11-15T16:17:27+09:00",
          "public_release_date": "2018-11-14T00:00:00+09:00",
          "status": "final",
          "version": "3.0.0",
          "revision_history": [
            {
              "date": "2018-11-15T16:17:27+09:00",
              "number": "1.0.0",
              "summary": "[2018年11月15日] 掲載"
            },
            {
              "date": "2018-11-20T10:37:07+09:00",
              "number": "2.0.0",
              "summary": "[2018年11月20日] CVSS による深刻度：内容を更新"
            },
            {
              "date": "2025-04-06T02:00:00+09:00",
              "number": "3.0.0",
              "summary": "XML形式からJSON形式に変換"
            }
          ]
        },
        "publisher": {
          "category": "coordinator",
          "name": "IPA",
          "namespace": "https://www.ipa.go.jp"
        },
        "references": [
          {
            "category": "external",
            "summary": "hitachi-sec-2018-133",
            "url": "http://www.hitachi.co.jp/Prod/comp/soft1/global/security/info/vuls/hitachi-sec-2018-133/index.html",
            "type": "vendor",
            "source": "Hitachi Software Vulnerability Information"
          },
          {
            "category": "external",
            "summary": "Article ID:100000477",
            "url": "https://www.veritas.com/support/en_US/article.100000477.html",
            "type": "vendor",
            "source": "Support"
          },
          {
            "category": "external",
            "summary": "Article ID:100043979",
            "url": "https://www.veritas.com/support/en_US/article.100043979.html",
            "type": "vendor",
            "source": "Support"
          },
          {
            "category": "external",
            "summary": "hitachi-sec-2018-133",
            "url": "http://www.hitachi.co.jp/Prod/comp/soft1/security/info/vuls/hitachi-sec-2018-133/index.html",
            "type": "vendor",
            "source": "ソフトウェア製品セキュリティ情報"
          }
        ]
      },
      "product_tree": {
        "branches": [
          {
            "category": "vendor",
            "name": "ベリタス",
            "product": {
              "product_id": "jvnpid:1.0::veritas:netbackup",
              "name": "Veritas NetBackup",
              "product_identification_helper": {
                "cpe": "cpe:2.3:a:veritas:netbackup:*:*:*:*:*:*:*:*"
              }
            }
          },
          {
            "category": "vendor",
            "name": "日立",
            "product": {
              "product_id": "jvnpid:1.0::hitachi:jp1_veritas_netbackup",
              "name": "JP1/VERITAS NetBackup",
              "product_identification_helper": {
                "cpe": "cpe:2.3:a:hitachi:jp1_veritas_netbackup:*:*:*:*:*:*:*:*"
              }
            }
          }
        ]
      },
      "vulnerabilities": [
        {
          "cve": "",
          "cwes": [
            {
              "id": "CWE-noinfo",
              "name": "情報不足",
              "version": "",
              "source": "IPA"
            }
          ],
          "product_status": {
            "known_affected": [
              "jvnpid:1.0::veritas:netbackup",
              "jvnpid:1.0::hitachi:jp1_veritas_netbackup"
            ]
          },
          "threats": [
            {
              "category": "impact",
              "details": "想定される影響については、ベンダ情報をご確認ください。"
            }
          ],
          "remediations": [
            {
              "category": "vendor_fix",
              "details": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。",
              "product_ids": [
